use std::fs;
use std::os::windows::process::CommandExt;
use std::path::PathBuf;
use std::process::Command;
use tracing::{error, info};

const CREATE_NO_WINDOW: u32 = 0x08000000;

/// Define the elevated task name
pub const TASK_NAME: &str = r#"\WSLDashboard\WSLDashboardTask"#;

/// Get the script storage directory (~/.wsldashboard/scripts)
pub fn get_scripts_dir() -> PathBuf {
    let home_dir = dirs::home_dir().unwrap_or_else(|| PathBuf::from("."));
    home_dir.join(".wsldashboard").join("scripts")
}

/// Get the path for the scheduled task intermediary script
pub fn get_script_path() -> PathBuf {
    get_scripts_dir().join("task_scheduler.ps1")
}

/// Ensure the scheduled task intermediary script exists and its content is correct
pub fn ensure_task_script_exists() -> Result<PathBuf, String> {
    let scripts_dir = get_scripts_dir();
    if !scripts_dir.exists() {
        fs::create_dir_all(&scripts_dir)
            .map_err(|e| format!("Failed to create scripts directory: {}", e))?;
    }

    let exe_path = std::env::current_exe().unwrap_or_else(|_| PathBuf::from("wsldashboard.exe"));
    let exe_str = exe_path.to_string_lossy();
    let script_path = get_script_path();

    let script_content = format!(
        "# Auto-generated by WSL Dashboard for elevated network automation\n\
         $exePath = \"{}\"\n\
         Start-Process -FilePath $exePath -ArgumentList \"/scheduler\" -WindowStyle Hidden -Wait",
        exe_str
    );

    fs::write(&script_path, script_content)
        .map_err(|e| format!("Failed to write task script: {}", e))?;
    Ok(script_path)
}

/// Request UAC authorization to create an elevated scheduled task (RL HIGHEST)
///
/// Uses the verified ShellExecuteEx + run_invisible_elevated_command channel to execute schtasks.
/// /TR points to the .ps1 script so that the path can be silently updated later by modifying the script with normal privileges.
pub fn register_task_with_elevation() -> Result<(), String> {
    let script_path = ensure_task_script_exists()?;
    let script_str = script_path.to_string_lossy();

    // Construct the schtasks /Create command line
    // /TR executes the PowerShell script, using -WindowStyle Hidden to ensure no window is shown
    let tr_value = format!(
        "powershell.exe -ExecutionPolicy Bypass -WindowStyle Hidden -File \"{}\"",
        script_str
    );
    let schtasks_cmd = format!(
        "schtasks /Create /TN \"{}\" /TR \"{}\" /SC ONLOGON /RL HIGHEST /F",
        TASK_NAME, tr_value
    );

    info!(
        "Registering scheduled task via elevated schtasks: TN={}, TR={}",
        TASK_NAME, tr_value
    );

    // Execute via verified ShellExecuteEx elevation channel (waits synchronously for completion)
    crate::utils::system::run_invisible_elevated_command(&schtasks_cmd)
}

/// Check if the elevated task exists
pub fn check_task_exists() -> bool {
    tracing::debug!("Checking if task exists: {}", TASK_NAME);
    let output = Command::new("schtasks")
        .args(&["/Query", "/TN", TASK_NAME])
        .creation_flags(CREATE_NO_WINDOW)
        .output();

    if let Ok(out) = output {
        out.status.success()
    } else {
        false
    }
}

/// Delete the elevated scheduled task with UAC authorization
pub fn unregister_task_with_elevation() -> Result<(), String> {
    // 1. Delete the scheduled task via elevated command
    let schtasks_cmd = format!("schtasks /Delete /TN \"{}\" /F", TASK_NAME);

    info!(
        "Unregistering scheduled task via elevated schtasks: TN={}",
        TASK_NAME
    );
    crate::utils::system::run_invisible_elevated_command(&schtasks_cmd)?;

    // 2. Delete the task folder via elevated command
    // Extract folder name from TASK_NAME (e.g., "\WSLDashboard\WSLDashboardTask" -> "\WSLDashboard")
    if let Some(last_backslash) = TASK_NAME.rfind('\\') {
        let folder_name = &TASK_NAME[..last_backslash];
        if !folder_name.is_empty() {
            let delete_folder_cmd = format!("schtasks /Delete /TN \"{}\" /F", folder_name);

            info!("Attempting to delete task folder: {}", folder_name);
            // Ignore errors here as the folder might not be empty or might have other tasks
            let _ = crate::utils::system::run_invisible_elevated_command(&delete_folder_cmd);
        }
    }

    // 3. Clean up the script file after task deletion
    let script_path = get_script_path();
    if script_path.exists() {
        info!("Cleaning up task script: {:?}", script_path);
        if let Err(e) = fs::remove_file(&script_path) {
            error!("Failed to remove task script: {}", e);
        }
    }

    // 4. Clean up the scripts directory if empty
    let scripts_dir = get_scripts_dir();
    if scripts_dir.exists() {
        if let Ok(entries) = fs::read_dir(&scripts_dir) {
            if entries.count() == 0 {
                info!("Cleaning up empty scripts directory: {:?}", scripts_dir);
                let _ = fs::remove_dir(&scripts_dir);
            }
        }
    }

    Ok(())
}
